name: Build and deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN_1 }}
        name: The Bot
        email: bot@bot.com  
    - name: npm build and deploy
      run: |
        npm install
        npm run build
        npm run deploy
      env:
        CI: true
